<a href="https://colab.research.google.com/github/Cazzarooo/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [12]:
# Array 1D

d1 = np.array([1,2,3])
print(d1)

[1 2 3]


In [13]:
d1.shape

(3,)

In [14]:
d1.ndim

1

In [15]:
d1.dtype

dtype('int64')

In [16]:
#Array 2D

d2 = np.array([[1,2,3], [4,5,6]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [17]:
d2.shape

(2, 3)

In [18]:
d2.ndim

2

In [19]:
d2.dtype

dtype('int64')

In [20]:
#Array 3D

d3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
d3.shape

(2, 2, 2)

In [22]:
d3.ndim

3

In [23]:
d3.dtype

dtype('int64')

In [ ]:
# Somando Listas

In [26]:
a = np.array([2,3,4])
b = np.array([2,3,4])

In [27]:
result = np.add(a, b)
print(result)

[4 6 8]


In [ ]:
# Selecionando itens em Arrays

In [33]:
c = np.array([[2,3,4,5], [6,7,8,9]])
print(c)

[[2 3 4 5]
 [6 7 8 9]]


In [34]:
# array[row,column]

c[1,2]

8

In [37]:
c[0,:]

array([2, 3, 4, 5])

In [38]:
c[:, 1]

array([3, 7])